---
title: "Cleaning MEP data"
author: "Ben Deck"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load required packages

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyverse)
library(data.table)
library(ggplot2)
library(reshape2)
library(lme4)
library(lmerTest)
```


Load all MEP data into memory
```{r, echo=FALSE,warning=FALSE,message=FALSE}

dataDir <- '/Users/Ben/Google Drive/CogNeW Laboratory Files/Projects/CEST-Motor/Data/Active/'
datFiles <- list.files(path = dataDir, pattern = '*\\.txt',
                       recursive = T, full.names = T)
```


```{r, echo=FALSE,warning=FALSE,message=FALSE}



Process_single_sub <- function(datFiles) {
  
  #dependencies
  library(tidyverse)
  library(tools)
  
  # read data
  mepdat <- read.delim(datFiles, encoding = )
  
  names(mepdat)[names(mepdat) == 'X1.Channel.1'] <- 'Mep_AMP'
  mepdat$FI_info <-basename(datFiles)
  mepdat <- as.data.frame(mepdat)
  return(mepdat)
  
}



MEP.list <- lapply(datFiles, Process_single_sub)
mep_list <- rbindlist(MEP.list)
mep_list$ID <- regmatches(mep_list$FI_info, regexpr(text = mep_list$FI_info, pattern = '^S[0-9]{2}|S[0-9]|^s[0-9]{2}|s[0-9]'))

mep_list$Timepoint <- as.factor(regmatches(mep_list$FI_info, regexpr(text = mep_list$FI_info, pattern = 'baseline|post[0-9]|post[0-9]{2}')))
mep_list$session <- ifelse(mep_list$Timepoint=='baseline', 'pre','post')

```



```{r, echo=FALSE, warning=FALSE,message=FALSE}



ggplot(mep_list, aes(x = Timepoint, y = Mep_AMP, color = ID, group = ID)) +
  geom_point(stat = 'summary') + geom_line(stat = 'summary') + ylim(0,5)

ggplot(mep_list, aes(x = Timepoint, y =Mep_AMP)) + geom_violin() + ylim(0,8)



```



```{r, echo= FALSE,warning=FALSE,message=FALSE}
baseline <- subset.data.frame(mep_list[which(Timepoint == "baseline")])
post0 <- subset.data.frame(mep_list[which(Timepoint == "post0")])
post10 <- subset.data.frame(mep_list[which(Timepoint == "post10")])
post20 <- subset.data.frame(mep_list[which(Timepoint == "post20")])
post30 <- subset.data.frame(mep_list[which(Timepoint == "post30")])


```


Count all meps so you can duplicate the cest data
```{r}
all_counts <- data.frame(table(mep_list$ID[mep_list$Timepoint != 'baseline']))
all_counts
counts<-data.frame(table(baseline$ID))
#counts$Var1 <- as.factor(counts$Var1)
counts
```

Load Cest data
```{r}
cest <- read.csv('/Users/Ben/Google Drive/CogNeW Laboratory Files/Projects/CEST-Motor/Data/Active/Cest_long.csv')

cest <- cest %>%
  rename(
    ID= ï..ID
  )

cest$label <- as.factor(cest$label)
cest$session <- factor(cest$session, levels = c('pre','post'))

```

Restructure data to have labels as columns
```{r}

cest <- na.omit(cest)

cest_wide <- cest %>%
  spread(label, mean_cest)

cest_wide

```
duptimes for active
```{r}
duptimes <- c(32 ,160, 40, 165, 40, 152, 39, 80, 35, 159, 40, 160, 41, 167, 40, 157, 45, 159,40, 160)

idx <- rep(1:nrow(cest_wide), duptimes)

dupcest <- cest_wide[idx,]

```


duptimes for sham
#```{r}
duptimes <- c(40 ,158, 40, 159, 40, 158, 29, 118)

idx <- rep(1:nrow(cest_wide), duptimes)

dupcest <- cest_wide[idx,]

#```

Left and right hemisphere cest value boxplot and dot plots

```{r}

ggplot(subset(cest, label %in% c("1024")), aes(session, mean_cest)) + 
  geom_boxplot() + 
  #ylim(.06, .09) +
  labs(title = 'Left Hemisphere M1 Mean Cest change distribution')

ggplot(subset(cest, label %in% c("1024")), aes(session, mean_cest, color = ID)) + 
  geom_point() +
  geom_line() +
  #ylim(.06, .09) +
  labs(title = 'Left Hemisphere M1 Mean Cest change per person')


ggplot(subset(cest, label %in% c("2024")), aes(session, mean_cest)) + 
  geom_boxplot() + 
  #ylim(.06, .09) + 
  labs(title = 'Right Hemisphere M1 Mean Cest change distribution')


ggplot(subset(cest, label %in% c("2024")), aes(session, mean_cest, color = ID)) + 
  geom_point() +
  geom_line() +
  #ylim(.06, .09) + 
  labs(title = 'Right Hemisphere M1 Mean Cest change per person')


```

```{r}
pre_cest_data <- subset.matrix(dupcest, dupcest$session =='pre')
post_cest_data <-  subset.matrix(dupcest, dupcest$session =='post')
lh.precentral_change <-  pre_cest_data$`1024` - post_cest_data$`1024`

pre_mep <- subset.matrix(mep_list, mep_list$session=='pre')
avg_pre_mep <- mean(pre_mep$Mep_AMP)
post_mep <- subset.matrix(mep_list, mep_list$session=='post')
mep_change <-  avg_pre_mep - post_mep$Mep_AMP
post_mep <- post_mep %>% group_by(ID) %>% mutate(counter =row_number(ID))


cest_mep_model1 <- lmerTest::lmer(mep_change ~ lh.precentral_change*post_mep$Timepoint + (1|post_mep$ID), REML = FALSE)
summary(cest_mep_model1)



cest_mep_model2 <- lmerTest::lmer(mep_change ~ lh.precentral_change*post_mep$Timepoint + (1 + post_mep$counter|post_mep$ID), REML = FALSE)
summary(cest_mep_model2)

anova(cest_mep_model1, cest_mep_model2)


plot(cest_mep_model1)
plot(cest_mep_model2)

```

```{r}

t.test(pre_cest_data['1024'], post_cest_data['1024'])



```
